[package]
name = "clarity"
version = "2.1.1"
authors = [
  "Jude Nelson <jude@stacks.org>",
  "Aaron Blankstein <aaron@blockstack.com>",
  "Ludo Galabru <ludovic@blockstack.com>",
]
license = "GPL-3.0-only"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
description = "Reference implementation of the Clarity virtual machine"
keywords = ["stacks", "stx", "bitcoin", "crypto", "blockchain"]
readme = "README.md"
edition = "2021"
resolver = "2"

[lib]
name = "clarity"
path = "./src/libclarity.rs"

[dependencies]
rand = "0.7.3"
rand_chacha = "=0.2.2"
serde = "1"
serde_derive = "1"
serde_stacker = { version = "0.1", optional = true }
regex = "1"
lazy_static = "1.4.0"
integer-sqrt = "0.1.3"
slog = { version = "2.5.2", features = ["max_level_trace"], optional = true }
stacks_common = { package = "stacks-common", path = "../stacks-common/.", optional = true, default-features = false }

[dependencies.serde_json]
version = "1.0"
features = ["arbitrary_precision", "unbounded_depth"]

[dependencies.rusqlite]
version = "=0.27.0"
features = ["blob", "serde_json", "i128_blob", "bundled", "trace"]
optional = true

[dependencies.time]
version = "0.2.23"
features = ["std"]

[dev-dependencies]
rstest = "0.11.0"
rstest_reuse = "0.1.3"
assert-json-diff = "1.0.0"
# a nightly rustc regression (35dbef235 2021-03-02) prevents criterion from compiling
#  but it isn't necessary for tests: only benchmarks. therefore, commenting out for now.
# criterion = "0.3"

[features]
default = ["developer-mode", "canonical", "log"]
canonical = ["sqlite", "stacks_common/canonical", "serde_stacker"]
log = ["slog", "stacks_common/log"]
sqlite = ["rusqlite"]
wasm = ["stacks_common/wasm", "developer-mode"]
developer-mode = ["stacks_common/developer-mode"]
slog_json = ["stacks_common/slog_json"]
testing = ["canonical"]

[profile.dev.package.regex]
opt-level = 2

[target.'cfg(all(target_arch = "x86_64", not(target_env = "msvc")))'.dependencies]
sha2-asm = "0.5.3"
